### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#864]
Let's add search capabilities to electronjs.org! 

Here's a hypothetical results page using data we already have:

# Results for 'ipc'

> IPC stands for Inter-Process Communication. Electron uses IPC to send serialized JSON messages between the main and renderer processes. - [Electron Glossary](https://electronjs.org/docs/glossary#ipc)

## Tutorials (2)

- **Quick Start**: In Electron, we have several ways to communicate between the _main process_ and _renderer processes_...
- **Online/Offline Event Detection**: Using Electron's _inter-process communication utilities_, the events can be forwarded to the main process and handled as needed

## Electron APIs (4)

- **ipcMain**: Communicate asynchronously from the main process to renderer processes.
- **ipcRenderer**: Communicate asynchronously from a renderer process to the main process.
- **remote**: Use main process modules from the renderer process.
- **<webview\> Tag**: Display external web content in an isolated frame and process.

## npm Modules (22)

- [pull-ipc](http://ghub.io/pull-ipc) - pull-stream wrapper around electron\'s ipc channel
- [electron-rpc](http://ghub.io/electron-rpc) - A lightweight rpc-style wrapper for the ipc module of electron
- [electron-ipc-stream](http://ghub.io/electron-ipc-stream) - Duplex stream over IPC for main/renderer to communicate with each other.
- [electron-ipc-broadcast](http://ghub.io/electron-ipc-broadcast) - Broadcast IPC messages to all Electron processes.
- [electron-ipc-mock](http://ghub.io/electron-ipc-mock) - Mocked electron ipc communication module
- [electron-ipc-promise](http://ghub.io/electron-ipc-promise) - electron ipc promise
- [electron-ipc-reactive](http://ghub.io/electron-ipc-reactive) - Reactive Elements for Electron via IPC
- [electron-ipc-responder](http://ghub.io/electron-ipc-responder) - A simple request/response based communication protocol for Electrons IPC functionality
- [electron-ipc-server](http://ghub.io/electron-ipc-server) - An IPC server with an API similar to Express.js\' for Electron
- [electron-ipc-socket](http://ghub.io/electron-ipc-socket) - Response-request abstraction on top of Electron IPC system.
- [electron-ipc-tunnel](http://ghub.io/electron-ipc-tunnel) - Create tunelled conncections over Electron\'s IPC.
- [electron-ipc](http://ghub.io/electron-ipc) - IPC for Electron using promises
- [electron-irpc](http://ghub.io/electron-irpc) - inter-process communication(IPC) and remote procedure call (RPC) combined.
- [electron-renderer-value](http://ghub.io/electron-renderer-value) - Get a value as a promise from an electron renderer process
- [electron-safe-ipc](http://ghub.io/electron-safe-ipc) - Safe communication between main process and renderer processes in Electron
- [elekiter](http://ghub.io/elekiter) - express like electron ipc wrapper library
- [falcor-electron](http://ghub.io/falcor-electron) - falcor integration for electron\'s ipc module
- [hadron-ipc](http://ghub.io/hadron-ipc) - Simplified IPC for electron apps.
- [ipc-electron-dispatcher](http://ghub.io/ipc-electron-dispatcher) - A flux dispatcher that talks through the process barrier for electron apps using ipc
- [ipc-promise](http://ghub.io/ipc-promise) - ipc use as Promises
- [other-window-ipc](http://ghub.io/other-window-ipc) - IPC between windows for Electron
- [pauls-electron-rpc](http://ghub.io/pauls-electron-rpc) - My RPC solution for exporting APIs from the electron background process to renderers and webviews.
- [redux-electron-ipc](http://ghub.io/redux-electron-ipc) - Redux Electron IPC Middleware

## GitHub Repos (28)

- [seanchas116/electron-safe-ipc](https:/github.com/seanchas116/electron-safe-ipc) - Safe communication between main process and renderer processes in ElectronElectron
- [SimulatedGREG/HipClip](https:/github.com/SimulatedGREG/HipClip) - A minimal clipboard history app.
- [WillStreeter/electron-process-ipc](https:/github.com/WillStreeter/electron-process-ipc) - Refactored electron-process to work with in my Electron/Angular2 project
- [ZombieHippie/go-electron-ipc-experiment](https:/github.com/ZombieHippie/go-electron-ipc-experiment) - Experimenting with packaging Go code to communicate with electron
- [bmathews/electron-ipc-bug](https:/github.com/bmathews/electron-ipc-bug) - null
- [coderhaoxin/electron-ipc](https:/github.com/coderhaoxin/electron-ipc) - [electron-ipc] a tiny wrapper of electron ipc api
- [Darkade/electron-ipc](https:/github.com/Darkade/electron-ipc) - quick example of communication between windows
- [dripcap/dripcap-release-playground](https:/github.com/dripcap/dripcap-release-playground) - null
- [dripcap/paperfilter](https:/github.com/dripcap/paperfilter) - null
- [EDOlsson/ipc-demo](https:/github.com/EDOlsson/ipc-demo) - IPC Demo from Pluralsight Electron-JS course
- [gigafied/electron-ipc](https:/github.com/gigafied/electron-ipc) - Electron. IPC. Promises
- [giovannipcarvalho/speedreader](https:/github.com/giovannipcarvalho/speedreader) - null
- [greggman/other-window-ipc](https:/github.com/greggman/other-window-ipc) - IPC between windows in Electron
- [gurudeb/electron-ipc-demo](https:/github.com/gurudeb/electron-ipc-demo) - Electron IPC Demo App
- [hiroshi-cl/electron-ipc](https:/github.com/hiroshi-cl/electron-ipc) - null
- [iamale/flux-over-electron-ipc](https:/github.com/iamale/flux-over-electron-ipc) - Flux over Electron IPC, inspired by https://medium.com/@nsisodiya/flux-inside-web-workers-cc51fb463882
- [imtaehyun/ssg-zipcd-tester-electron](https:/github.com/imtaehyun/ssg-zipcd-tester-electron) - null
- [jfilipczyk/lesson-report](https:/github.com/jfilipczyk/lesson-report) - Settlement report based on calendar events
- [mongodb-js/hadron-ipc](https:/github.com/mongodb-js/hadron-ipc) - Simplified IPC for electron apps.
- [napcs/ElectronTipCalc](https:/github.com/napcs/ElectronTipCalc) - Tip calculator in Electron
- [ngochuy/electron-react-ipc](https:/github.com/ngochuy/electron-react-ipc) - Electron app with react integrated and accept ipc request from external app.
- [KimuraTakaumi/electron-ipc](https:/github.com/KimuraTakaumi/electron-ipc) - null
- [saan1984/ElectronIPCDemo](https:/github.com/saan1984/ElectronIPCDemo) - ElectronIPCDemo
- [sandipchitale/ePOM360](https:/github.com/sandipchitale/ePOM360) - A simple electron based tool to get a 360 view of Maven POM.
- [sandipchitale/eportmon](https:/github.com/sandipchitale/eportmon) - A simple electron based Portmon
- [sandipchitale/eyes](https:/github.com/sandipchitale/eyes) - Electronic eyes
- [sasaplus1/ipc-promise](https:/github.com/sasaplus1/ipc-promise) - ipc use as Promises
- [stefanjudis/electron-ipc-example](https:/github.com/stefanjudis/electron-ipc-example) - Example repo for IPC talk
- [willSonic/electron-background-process-ipc-app](https:/github.com/willSonic/electron-background-process-ipc-app) - test bed for electron-process-ipc

---
🎬

The following Data sources were used to compile this example:

- [electron-i18n](https://github.com/electron/electron-i18n#usage)
- [electron-npm-packages](https://github.com/zeke/electron-npm-packages)
- [repos-using-electron](https://github.com/zeke/repos-using-electron)

Try it at home:

```sh
npm i -g trymodule && trymodule repos-using-electron=repos electron-npm-packages=packages
```

Find IPC GitHub repos:

```js
repos.filter(repo => repo.fullName.match(/ipc/i)).map(repo => `- [${repo.fullName}](https:/github.com/${repo.fullName}) - ${repo.description}`).join('
')
```

Find IPC npm packages:

```js
packages.filter(p => p.name.match(/ipc/i) || p.description.match(/ipc/i) || (p.keywords || []).map(w => w.toLowerCase()).includes('ipc')).map(p => `- [${p.name}](http:/ghub.io/${p.name}) - ${p.description}`).join('
')
```

## Task breakdown
- [x] docs as data source
- [x] `electron-npm-packages` as data source
- [x] endpoint can send results back as either HTML or JSON as per requested
- [x] support `repos-using-electron` as data source (pending [electron/repos-using-electron#24](https://github.com/electron/repos-using-electron/pull/24))
- [x] break down search result view into partials per data source
- [ ] pagination
